throw new Error('Error was thrown in worker')
